spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student
    username: root
    password: admin1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    servlet:
      path: /api

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: com.abstractionizer.studentInformationSystem.6/db/rmdb/mappers/*Mapper.xml

redis:
  port: 6379
  host: localhost
  pool:
    maxIdle: 8
    minIdle: 0
    maxActive: -1
    maxWait: 30000

